local WelTo = LibStub:GetLibrary('WelTo-1.0')
WelTo.Text={
	"你好啊，%name，你一定是一个有文化的的%class吧" ,
	"嗨！我们又多了一位%class朋友，他就是%name。",
	"愿圣光与你同在，%race朋友。", 
	"WOOO~这不是%class%name么？",
	"欢迎来到%guild，%class。",
	"听说加入%guild后%name再也不是移动荣誉了……",
	"纳鲁没有忘记%name，指引他来到%guild。",
	"你好啊，%name，你见过一粒蛋么?",
	"%name你是来帮助%guild打败燃烧军团的吧！",
	"%name，多么美妙的名字啊！",
	"祝你生日快乐%name",
	"愿风指引你的道路，%name。",
	"有没有玩传奇的感觉，%name？",
	"花儿对你笑，%name，我代表花儿欢迎你的到来。",
	"[%race语]欢迎，%name。",
	"%name听起来像个%race，%race%class",
	"%name，听起来很好吃啊……",
	"%name，你是不是美女阿？",
	"欢迎来到%guild，今后法师们会很乐意提供你面包的。",
	"新来的%class要不要一起去英雄模式的死亡矿井",
	"欢迎来到%guild，这里就是你的家，拿着这个炉石，%name，它是给你的。",
	"%zone？%name，你能说说怎么才能过去么",
	"欢迎来到%guild，%race",
	"欢迎来到%guild，%name",
	"[%name]<=刚捡到的",
	"帮我教训下在%zone的部落吧，%name",
	"越宅越厉害……%name",
	"为了%guild而战！",
	"%name，扬起你的沙砾，遮蔽太阳的光芒吧!",
	"种族不代表荣耀，%race",
	"欢迎参加这场盛宴。%name，狂欢至死吧!",
	"时间就是金钱，%name",
	"这有活人！%name",
	"感谢你%name,哈卡再也无法控制我了 ",
	"生命本身毫无意义，只有加入%guild才能让你感受到生命的真谛 ",
	"愿星辰指引你的道路。%name",
	"这就是好奇的代价，%class",
	"Doral ana'diel? %name",
	"%name，范克里夫正悬赏你的头颅",
	"%race，我们正在上课！",
	"复活吧，我的勇士！为你而战，我的%name！",
	"尘归尘，土归土！%name归%name",
	"要记住你公会的名字，%name！",
	"%name想吃肉了。",
	"骄傲会将你送上绝路。来吧，%name，品尝夺灵者的愤怒吧！ ",
	"你的加入，将成为同伴的榜样。%name",
	"颤抖吧,%name! ",
	"我们以鲜血捍卫荣誉! %name",
	"Now,...%name...,we are one",
	"没人生来杰出。%class",
	"我们是%guild，不能让复仇的情绪占据我们的意识。",
	"我希望在我介绍完自己前，%name没有掉线",
	"和我聊聊吧，%name",
}
